finished 5 pro.
Yareda21/class pull request #8
Opened 2024-08-26 13:08 UTC by Merry1035

calc

2024-08-27 12:19 UTC, Yareda21 commented on chat_bot.py
this is not a chat bot, there should be a list or dictionary to select answer from,

2024-08-27 12:22 UTC, Yareda21 requested changes
please follow the comments and do the project again

2024-08-27 12:22 UTC, Yareda21 commented on guess_game.py
you should be using random number generator, rather than just saying num = 6
import random 

num = random.randint(0,100)

use this

2024-08-27 12:22 UTC, Yareda21 commented on todo_list.py
i asked you to do a todo list, not registration form. please visit your code again

2024-08-28 11:53 UTC, Merry1035 commented on guess_game.py
tnx

2024-08-28 12:11 UTC, Merry1035 commented on guess_game.py
ok tnx

2024-08-28 12:11 UTC, Merry1035 commented on todo_list.py
i will

2024-08-29 11:59 UTC, merged